### ISSUE TITLE
Java 11 - Fatal error condition occurred in /work/src/native/crt.c:112

### ISSUE THREAD

**Issue by rajithd-aurea** [awslabs/aws-crt-java#316]
Application is crashing with following error in log. Any idea what is causing this issue and why its crashing the application ?
Version - `software.amazon.awssdk:aws-crt-client:2.14.13-PREVIEW`
Java version - `OpenJDK Runtime Environment Corretto-11.0.11.9.1 (build 11.0.11+9-LTS)`

Notice this error when running load testing our application. Not all requests are failing, but when it fails with this error application is crashing. 

```
2021-05-04 23:24:00.753 ERROR 4923 --- [      Thread-23] s.a.a.h.c.i.AwsCrtAsyncHttpStreamAdapter : Response Encountered an Error.
software.amazon.awssdk.crt.http.HttpException: A callback has reported failure.
        at software.amazon.awssdk.http.crt.internal.AwsCrtAsyncHttpStreamAdapter.onResponseComplete(AwsCrtAsyncHttpStreamAdapter.java:116) ~[aws-crt-client-2.14.13-PREVIEW.jar!/:na]
        at software.amazon.awssdk.crt.http.HttpStreamResponseHandlerNativeAdapter.onResponseComplete(HttpStreamResponseHandlerNativeAdapter.java:31) ~[aws-crt-0.8.2.jar!/:0.8.2]

2021-05-04 23:24:00.753 ERROR 4923 --- [      Thread-23] s.a.a.h.c.i.AwsCrtResponseBodyPublisher  : Error processing Response Body

software.amazon.awssdk.crt.http.HttpException: A callback has reported failure.
        at software.amazon.awssdk.http.crt.internal.AwsCrtAsyncHttpStreamAdapter.onResponseComplete(AwsCrtAsyncHttpStreamAdapter.java:116) ~[aws-crt-client-2.14.13-PREVIEW.jar!/:na]
        at software.amazon.awssdk.crt.http.HttpStreamResponseHandlerNativeAdapter.onResponseComplete(HttpStreamResponseHandlerNativeAdapter.java:31) ~[aws-crt-0.8.2.jar!/:0.8.2]

2021-05-04 23:24:00.753 ERROR 4923 --- [      Thread-23] s.a.a.h.c.i.AwsCrtResponseBodyPublisher  : Error before ResponseBodyPublisher could complete: A callback has reported failure.
```

```
Fatal error condition occurred in /work/src/native/crt.c:112: !(*env)->ExceptionCheck(env)
Exiting Application
################################################################################
Resolved stacktrace:
################################################################################
################################################################################
Raw stacktrace:
################################################################################
```

**Comment by bretambrose** [comment]
Can you enable CRT logging and attach the log from a failing run (can trim to the last portion)?  CRT logging can be enabled by setting system properties per https://github.com/awslabs/aws-crt-java/blob/main/src/main/java/software/amazon/awssdk/crt/Log.java#L22:

-Daws.crt.log.level=Debug -Daws.crt.log.destination=File -Daws.crt.log.filename=/tmp/log.txt

or similar.

Trace level will likely be overwhelmingly verbose (and we don't have log rotation implemented yet) so maybe start with Debug.
