### ISSUE TITLE
AWS CRT bug

### ISSUE THREAD

**Issue by PrudviRajChiluvuri** [awslabs/aws-crt-java#692]
### Describe the bug

I am getting below exception while downloading object from AWS S3

### Expected Behavior

It should able to download s3 object to file system

### Current Behavior

Getting below exception : 

java.lang.UnsatisfiedLinkError: /usr/local/tomcat/temp/AWSCRT_2753490975965582941libaws-crt-jni.so: Error relocating /usr/local/tomcat/temp/AWSCRT_2753490975965582941libaws-crt-jni.so: pthread_getname_np: symbol not found
        at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[na:1.8.0_151]
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) ~[na:1.8.0_151]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) ~[na:1.8.0_151]
        at java.lang.Runtime.load0(Runtime.java:809) ~[na:1.8.0_151]
        at java.lang.System.load(System.java:1086) ~[na:1.8.0_151]
        at software.amazon.awssdk.crt.CRT.extractAndLoadLibrary(CRT.java:324) ~[aws-crt-0.25.0.jar:0.25.0]
        at software.amazon.awssdk.crt.CRT.loadLibraryFromJar(CRT.java:358) ~[aws-crt-0.25.0.jar:0.25.0]
        at software.amazon.awssdk.crt.CRT.<clinit>(CRT.java:41) ~[aws-crt-0.25.0.jar:0.25.0]
        at software.amazon.awssdk.crt.CrtResource.<clinit>(CrtResource.java:104) ~[aws-crt-0.25.0.jar:0.25.0]
        at software.amazon.awssdk.services.s3.internal.crt.S3NativeClientConfiguration.<init>(S3NativeClientConfiguration.java:69) ~[s3-2.20.139.jar:na]
        at software.amazon.awssdk.services.s3.internal.crt.S3NativeClientConfiguration$Builder.build(S3NativeClientConfiguration.java:241) ~[s3-2.20.139.jar:na]
        at software.amazon.awssdk.services.s3.internal.crt.DefaultS3CrtAsyncClient.initializeS3CrtAsyncHttpClient(DefaultS3CrtAsyncClient.java:143) ~[s3-2.20.139.jar:na]
        at software.amazon.awssdk.services.s3.internal.crt.DefaultS3CrtAsyncClient.initializeS3AsyncClient(DefaultS3CrtAsyncClient.java:111) ~[s3-2.20.139.jar:na]
        at software.amazon.awssdk.services.s3.internal.crt.DefaultS3CrtAsyncClient.<init>(DefaultS3CrtAsyncClient.java:70) ~[s3-2.20.139.jar:na]
        at software.amazon.awssdk.services.s3.internal.crt.DefaultS3CrtAsyncClient.<init>(DefaultS3CrtAsyncClient.java:65) ~[s3-2.20.139.jar:na]
        at software.amazon.awssdk.services.s3.internal.crt.DefaultS3CrtAsyncClient$DefaultS3CrtClientBuilder.build(DefaultS3CrtAsyncClient.java:291) ~[s3-2.20.139.jar:na]
        at software.amazon.awssdk.services.s3.internal.crt.DefaultS3CrtAsyncClient$DefaultS3CrtClientBuilder.build(DefaultS3CrtAsyncClient.java:146) ~[s3-2.20.139.jar:na]
        

### Reproduction Steps

  public String downloadS3Object(String objectKey, String folder, String fileName)
            throws URISyntaxException, InterruptedException, ExecutionException, IOException {

       Files.createDirectories(Paths.get(folder));
        File file = new File(folder + fileName);

     // config
        S3CrtHttpConfiguration cfg = S3CrtHttpConfiguration.builder()
                .connectionTimeout(Duration.ZERO)
                .build();

        AwsBasicCredentials awsCredentials = AwsBasicCredentials.create(accessKey,
                secretKey);

        // s3client with try-with-resource
        try (S3AsyncClient s3Client = S3AsyncClient.crtBuilder()
                .credentialsProvider(StaticCredentialsProvider.create(awsCredentials))
                .region(Region.of(region))
                .endpointOverride(new URI(basePath))
                .targetThroughputInGbps(20.0)
                .minimumPartSizeInBytes(20 * 1025 * 1024L)
                .httpConfiguration(cfg)
                .maxConcurrency(10)
                .build()) {

            S3TransferManager transferManager = S3TransferManager.builder()
                    .s3Client(s3Client)
                    .build();
            
            DownloadFileRequest downloadFileRequest = DownloadFileRequest.builder()
                    .getObjectRequest(b -> b.bucket(bucketName).key(objectKey))
                    .addTransferListener(LoggingTransferListener.create())
                    .destination(file)
                    .build();

            // download
            transferManager.downloadFile(downloadFileRequest).completionFuture().join();

            return file.getAbsolutePath();
}

### Additional Information/Context

java version :  11

In ELASTIC KUBERNETES SERVICE : 

AMI type
AL2_x86_64

AMI release version
1.23.13-20230105

Instance types
t3a.large

in pom.xml
----------------
<dependency>
  <groupId>software.amazon.awssdk</groupId>
  <artifactId>s3</artifactId>
  <version>2.20.119</version>
</dependency>

<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>s3-transfer-manager</artifactId>
  <version>2.20.119</version>
</dependency>

<dependency>
  <groupId>software.amazon.awssdk.crt</groupId>
  <artifactId>aws-crt</artifactId>
  <version>0.24.0</version>
</dependency>

### aws-crt-java version used

0.24.0

### Java version used

11

### Operating System and version

amazon linux 1.23.13-20230105

**Comment by yasminetalby** [comment]
Hello @PrudviRajChiluvuri ,

Thank you very much for your submission. I have a couple of questions:
- Are you using MUSL?
- What is your Java runtime?

Best regards,

Yasmine
