### ISSUE TITLE
failed to get request id: interactive mode in container

### ISSUE THREAD

**Issue by jonathanyuechun** [awslabs/aws-crt-java#783]
### Describe the bug

the crt implementation of the aws sdk doest not work in a container executed in interactive mode.
a 500 error code is returned

This bug is easily reproductible by spinning up any java dev container and making request to a S3 instance.
Note: doing docker run -it <image> then running the compiled program won't work either but doing a docker run <image> java <program> will work successfully.

In debug mode, i can see the 500 code error is returned due to failure of getting the request_id

My guess is that it's a network issue where aws crt do not resolve correctly.

Using the non crt implementation works perfect...

### Expected Behavior

success in down and up

### Current Behavior

code 500 failed to get request id

### Reproduction Steps

devcontainer java (microsoft image)

any example of aws-java-sdk2

### aws-crt-java version used

0.28.11 and 0.29.18 and master (28/04/24)

### Java version used

opendjdk-17 and eclipse-temurin-17

### Operating System and version

ubuntu 20.04, 22.04

**Comment by jmklix** [comment]
Can you provide the dockerfile and minimal sample code that you're using to reproduce this? Also more detailed logs from when the error occurs would be helpful.

**Comment by jonathanyuechun** [comment]
Hi yes,

please consider:

```Dockerfile
# note jar is generated using build-stage of docker but for simplicity i removed this part
FROM eclipse-temurin:17

COPY target/app.jar ./app.jar

ENTRYPOINT ["java", "-XX:MaxRAMPercentage=80.0",  "-cp", "./app.jar", "com.samples.AppSample"]
```
**build and run**

```sh
docker build . -t myapp:latest

# works
docker run --rm --net host myapp:latest

# do not work
docker run -it --rm --net host myapp:latest bash
<dockershell>: java -XX:MaxRAMPercentage=80.0 -cp ./app.jar com.samples.AppSample
```

**stacktrace**

```sh
[main] ERROR com.mycompany.function.BlobHandler - The download (bucket=testcsv, key=retour.pdf) failed
java.util.concurrent.ExecutionException: software.amazon.awssdk.core.exception.SdkClientException: Failed to send the request: Response code indicates internal server error
at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
at com.mycompany.function.BlobHandler.downloadFile(BlobHandler.java:269) ~[classes/:?]
at com.mycompany.function.BlobHandler.handle(BlobHandler.java:225) [classes/:?]
at com.mycompany.Test.BasicJavaTest.run(BasicJavaTest.java:180) [classes/:?]
at com.mycompany.AppSample.main(AppSample.java:17) [classes/:?]
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Failed to send the request: Response code indicates internal server error
at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111) ~[sdk-core-2.21.43.jar:?]
at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:47) ~[sdk-core-2.21.43.jar:?]
at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.handleError(S3CrtResponseHandlerAdapter.java:139) ~[s3-2.21.43.jar:?]
at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.onFinished(S3CrtResponseHandlerAdapter.java:99) ~[s3-2.21.43.jar:?]
at software.amazon.awssdk.crt.s3.S3MetaRequestResponseHandlerNativeAdapter.onFinished(S3MetaRequestResponseHandlerNativeAdapter.java:24) ~[aws-crt-0.28.12.jar:0.28.12]
Exception in thread "main" java.util.concurrent.ExecutionException: software.amazon.awssdk.core.exception.SdkClientException: Failed to send the request: Response code indicates internal server error
at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
at com.mycompany.function.BlobHandler.downloadFile(BlobHandler.java:269)
at com.mycompany.function.BlobHandler.handle(BlobHandler.java:225)
at com.mycompany.Test.BasicJavaTest.run(BasicJavaTest.java:180)
at com.mycompany.AppSample.main(AppSample.java:17)
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Failed to send the request: Response code indicates internal server error
at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)
at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:47)
at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.handleError(S3CrtResponseHandlerAdapter.java:139)
at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.onFinished(S3CrtResponseHandlerAdapter.java:99)
at software.amazon.awssdk.crt.s3.S3MetaRequestResponseHandlerNativeAdapter.onFinished(S3MetaRequestResponseHandlerNativeAdapter.java:24)
```


**code snippet**


```java
AwsBasicCredentials credentials = AwsBasicCredentials.create("minioadmin", "minioadmin");
StaticCredentialsProvider credentialsProvider = StaticCredentialsProvider.create(credentials);

S3AsyncClient s3AsyncClient = S3AsyncClient.crtBuilder().credentialsProvider(credentialsProvider)
    .endpointOverride(new URI("http://" + "localhost:9000"))
    .region(Region.US_EAST_1)
    .forcePathStyle(true)
    .targetThroughputInGbps(1.0)
    .minimumPartSizeInBytes(4194304L)
    .checksumValidationEnabled(false)
    .build();
S3TransferManager transferManager = S3TransferManager.builder().s3Client(s3AsyncClient).build();

String bucketName = "...";
String key = "...";
InputStream fis = new FileInputStream("/tmp/test-minio-3.6g.tar");

BlockingInputStreamAsyncRequestBody body = AsyncRequestBody.forBlockingInputStream((Long) null);


Upload upload = transferManager.upload((builder) -> {
    builder.requestBody(body).addTransferListener(LoggingTransferListener.create()).putObjectRequest((req) -> {
        req.bucket(bucketName).key(key);
    }).build();
});


body.writeInputStream(fis);
upload.completionFuture().join();
```

**Comment by jonathanyuechun** [comment]
the above exception is reproductible in a vscode devcontainer using any of the provided microsoft java image

**Comment by jonathanyuechun** [comment]
sure it was, tested with the same snippet of code but using the non crt async client and i have a bunch of other services running on the same devcontainer interacting with the same minio

**Comment by jonathanyuechun** [comment]
any news ?

**Comment by jmklix** [comment]
Can you reproduce this using AWS s3? You seem to be using minio and that can behave slightly differently than AWS s3. It might have a bug that we can't fix/change. So to be able to help you most effectively we need a reproduction using AWS services.
